### ISSUE TITLE
Code execution error

### ISSUE THREAD

**Issue by FrancisBou** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#56]
The package in it's current state does not work as indicated on the readme.
Following the basic example gives me this error:

```
TypeError: Cannot read property 'insert' of undefined
at add (packages/msavin:sjobs/server/imports/actions/add/index.js:31:35)
at Object.Jobs.run (packages/msavin:sjobs/server/api.js:55:22)
at jobs.js (imports/server/startup/jobs.js:28:6)
at fileEvaluate (packages/modules-runtime.js:333:9)
at require (packages/modules-runtime.js:228:16)
at index.js (imports/server/startup/index.js:1:171)
at fileEvaluate (packages/modules-runtime.js:333:9)
at require (packages/modules-runtime.js:228:16)
at main.js (server/main.js:1:14)
at fileEvaluate (packages/modules-runtime.js:333:9)
```

**Comment by msavin** [comment]
Can you post your code + package list?

**Comment by FrancisBou** [comment]
I can't post code unfortunalety but I tested with the example from the README.

If it matters, I was using the version 2.0.1 and upgraded to 3.0.6
Meteor 1.6.0.1

**Comment by msavin** [comment]
Are you running the `run` function before the `register` function has
completed? You might want to wrap your `run` in `Meteor.startup` or run it
from `meteor shell`.

**Comment by FrancisBou** [comment]
Wrapping inside `Meteor.startup` solved the issue, thanks for your support @msavin
